#!/usr/bin/env python3
"""Count-query error rollup (MAE / MSE / RMSE) derived from benchmark_summary.csv.

Count queries return a number, so precision/recall don't apply. The benchmark
summary scores them with "count closeness" = max(0, 1 - |pred-gt|/gt). This
script adds the squared-error view (MSE/RMSE) that closeness deliberately omits,
without mutating benchmark_summary.csv (which the e2e report parses row-by-row
and which is regenerated by build_simple_benchmark_pdf.py).

Output: results/metrics/count_error_rollup.csv
"""
from __future__ import annotations

import csv
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "results" / "metrics" / "benchmark_summary.csv"
OUT = ROOT / "results" / "metrics" / "count_error_rollup.csv"

PRED_RE = re.compile(r"pred=(\d+)")
GT_RE = re.compile(r"ground truth=(\d+)")


def load_count_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    with SRC.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            notes = row.get("notes", "")
            if "count closeness" not in notes:
                continue
            pred_m, gt_m = PRED_RE.search(notes), GT_RE.search(notes)
            if not (pred_m and gt_m):
                continue
            pred, gt = int(pred_m.group(1)), int(gt_m.group(1))
            abs_err = abs(pred - gt)
            rel_err = abs_err / max(gt, 1)
            # bounded signed score: 0 = exact, + = over-count, - = under-count,
            # magnitude in [0,100] = how far. Symmetric, no clamp needed.
            signed_score = 100.0 * (pred - gt) / (pred + gt) if (pred + gt) else 0.0
            rows.append({
                "group": row["group"],
                "query": row["query"],
                "pred": pred,
                "ground_truth": gt,
                "signed_score_pct": signed_score,
                "abs_error": abs_err,
                "rel_error": rel_err,
                "squared_error": abs_err ** 2,
                "closeness_pct": max(0.0, 100.0 * (1.0 - rel_err)),
            })
    return rows


def main() -> None:
    rows = load_count_rows()
    if not rows:
        raise SystemExit(f"no count queries found in {SRC}")

    n = len(rows)
    mae = sum(r["abs_error"] for r in rows) / n
    mse = sum(r["squared_error"] for r in rows) / n
    rmse = math.sqrt(mse)

    # mean absolute signed count deviation (SCD) across the count family
    mean_abs_scd = sum(abs(r["signed_score_pct"]) for r in rows) / n

    fields = ["group", "query", "pred", "ground_truth", "abs_error",
              "rel_error", "squared_error", "closeness_pct", "signed_count_deviation_pct"]
    OUT.parent.mkdir(exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(fields)
        for r in rows:
            w.writerow([
                r["group"], r["query"], r["pred"], r["ground_truth"],
                r["abs_error"], f"{r['rel_error']:.4f}",
                r["squared_error"], f"{r['closeness_pct']:.2f}",
                f"{r['signed_score_pct']:+.2f}",
            ])
        # aggregate rollup rows (kept in this dedicated file, NOT in benchmark_summary.csv)
        w.writerow([])
        w.writerow(["ROLLUP", "count family (n=%d)" % n, "", "", "", "", "", "", ""])
        w.writerow(["ROLLUP", "MAE (mean abs error, actions)", "", "", f"{mae:.1f}", "", "", "", ""])
        w.writerow(["ROLLUP", "MSE (mean squared error)", "", "", "", "", f"{mse:.0f}", "", ""])
        w.writerow(["ROLLUP", "RMSE (actions)", "", "", f"{rmse:.1f}", "", "", "", ""])
        w.writerow(["ROLLUP", "mean |signed count deviation| (%)", "", "", "", "", "", "", f"{mean_abs_scd:.2f}"])

    print(f"wrote {OUT.relative_to(ROOT)}  (n={n})")
    print(f"  MAE  = {mae:,.1f} actions")
    print(f"  MSE  = {mse:,.0f}")
    print(f"  RMSE = {rmse:,.1f} actions")
    print(f"  mean |SCD| = {mean_abs_scd:.2f}%")


if __name__ == "__main__":
    main()
